
```{r}
library(Seurat)
library(dplyr)
library(patchwork)

#Samples noted below:

#E14.5 cervical
#A14, B14, C14, D14, E14, F14

#E16.5 cervical
#A16, C16, D16, E16, F16, G16, H16 (B16 produced poor emulsion and negligible cells were retrieved in sequencing data; omitted from this point)

#E16.5 thoracic - TBD
#TA16, TB16, TC16, TD16, TE16, TF16, TG16, TH16

#E16.5 lumbar
#LA16, LB16, LC16, LD16, LE16, LF16, LG16, LH16
```

```{r}
A14.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/14A/filtered_feature_bc_matrix")
B14.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/14B/filtered_feature_bc_matrix")
C14.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/14C/filtered_feature_bc_matrix")
D14.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/14D/filtered_feature_bc_matrix")
E14.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/14E/filtered_feature_bc_matrix")
F14.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/14F/filtered_feature_bc_matrix")
A14 <- CreateSeuratObject(A14.data, project = "A14")
B14 <- CreateSeuratObject(B14.data, project = "B14")
C14 <- CreateSeuratObject(C14.data, project = "C14")
D14 <- CreateSeuratObject(D14.data, project = "D14")
E14 <- CreateSeuratObject(E14.data, project = "E14")
F14 <- CreateSeuratObject(F14.data, project = "F14")
AB14 <- merge(A14, y = B14, project = "AB14")
CD14 <- merge(C14, y = D14, project = "CD14")
EF14 <- merge(E14, y = F14, project = "EF14")
AB14[["percent.mt.ab"]] <- PercentageFeatureSet(AB14, pattern = "^mt-")
CD14[["percent.mt.cd"]] <- PercentageFeatureSet(CD14, pattern = "^mt-")
EF14[["percent.mt.ef"]] <- PercentageFeatureSet(EF14, pattern = "^mt-")
VlnPlot(AB14, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.ab"), ncol = 3)
VlnPlot(CD14, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.cd"), ncol = 3)
VlnPlot(EF14, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.ef"), ncol = 3)
AB14 <- subset(AB14, subset = nFeature_RNA > 500 & percent.mt.ab < 5)
CD14 <- subset(CD14, subset = nFeature_RNA > 500 & percent.mt.cd < 5)
EF14 <- subset(EF14, subset = nFeature_RNA > 500 & percent.mt.ef < 5)
AB14 <- NormalizeData(AB14)
CD14 <- NormalizeData(CD14)
EF14 <- NormalizeData(EF14)
AB14 <- FindVariableFeatures(AB14, selection.method = "vst", nfeatures = 2000)
CD14 <- FindVariableFeatures(CD14, selection.method = "vst", nfeatures = 2000)
EF14 <- FindVariableFeatures(EF14, selection.method = "vst", nfeatures = 2000)
all.genes1 <- rownames(AB14)
all.genes2 <- rownames(CD14)
all.genes3 <- rownames(EF14)
AB14 <- ScaleData(AB14, features = all.genes1)
CD14 <- ScaleData(CD14, features = all.genes2)
EF14 <- ScaleData(EF14, features = all.genes3)
AB14 <- RunPCA(AB14, features = VariableFeatures(object = AB14), npcs=50)
CD14 <- RunPCA(CD14, features = VariableFeatures(object = CD14), npcs=50)
EF14 <- RunPCA(EF14, features = VariableFeatures(object = EF14), npcs=50)
DimHeatmap(AB14, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(AB14, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(AB14, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(AB14, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(AB14, dims = 37:45, cells = 500, balanced = TRUE)
DimHeatmap(CD14, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(CD14, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(CD14, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(CD14, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(CD14, dims = 37:45, cells = 500, balanced = TRUE)
DimHeatmap(EF14, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(EF14, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(EF14, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(EF14, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(EF14, dims = 37:45, cells = 500, balanced = TRUE)
AB14 <- FindNeighbors(AB14, dims = 1:30)
AB14 <- FindClusters(AB14, resolution = 1)
AB14 <- RunUMAP(AB14, dims = 1:30)
DimPlot(AB14, reduction = "umap", label = T)
CD14 <- FindNeighbors(CD14, dims = 1:30)
CD14 <- FindClusters(CD14, resolution = 1)
CD14 <- RunUMAP(CD14, dims = 1:30)
DimPlot(CD14, reduction = "umap", label = T)
EF14 <- FindNeighbors(EF14, dims = 1:30)
EF14 <- FindClusters(EF14, resolution = 1)
EF14 <- RunUMAP(EF14, dims = 1:30)
DimPlot(EF14, reduction = "umap", label = T)

#Save E14.5 Cervical filtered data as combined biological replicates
saveRDS(AB14, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/14AB_all.RDS")
saveRDS(CD14, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/14CD_all.RDS")
saveRDS(EF14, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/14EF_all.RDS")

rm(A14.data,B14.data,C14.data,D14.data,E14.data,F14.data)
```

```{r}
#QC plots Fig 1 supp:

pdf(file = "/Users/roomerb/QC_pre_nfeat.pdf", height = 6, width = 4)
VlnPlot(AB14, features = "nFeature_RNA", y.max = 11000)
dev.off()

pdf(file = "/Users/roomerb/QC_pre_mt.pdf", height = 6, width = 4)
VlnPlot(AB14, features ="percent.mt.ab", y.max = 65)
dev.off()

pdf(file = "/Users/roomerb/QC_post_nfeat.pdf", height = 6, width = 4)
VlnPlot(AB14, features = "nFeature_RNA", y.max = 11000)
dev.off()

pdf(file = "/Users/roomerb/QC_post_mt.pdf", height = 6, width = 4)
VlnPlot(AB14, features = "percent.mt.ab", y.max = 65)
dev.off()
rm(AB14, CD14, EF14)
```


```{r}
#Load & filter E16.5 cervical
A16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16A/filtered_feature_bc_matrix")
C16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16C/filtered_feature_bc_matrix")
D16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16D/filtered_feature_bc_matrix")
E16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16E/filtered_feature_bc_matrix")
F16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16F/filtered_feature_bc_matrix")
A16 <- CreateSeuratObject(A16.data, project = "A16")
C16 <- CreateSeuratObject(C16.data, project = "C16")
D16 <- CreateSeuratObject(D16.data, project = "D16")
E16 <- CreateSeuratObject(E16.data, project = "E16")
F16 <- CreateSeuratObject(F16.data, project = "F16")
CD16 <- merge(C16, y = D16, project = "E16CD")
EF16 <- merge(E16, y = F16, project = "E16EF")
A16[["percent.mt.a"]] <- PercentageFeatureSet(A16, pattern = "^mt-")
CD16[["percent.mt.cd"]] <- PercentageFeatureSet(CD16, pattern = "^mt-")
EF16[["percent.mt.ef"]] <- PercentageFeatureSet(EF16, pattern = "^mt-")
VlnPlot(A16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.a"), ncol = 3)
VlnPlot(CD16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.cd"), ncol = 3)
VlnPlot(EF16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.ef"), ncol = 3)
A16 <- subset(A16, subset = nFeature_RNA > 500 & percent.mt.a < 5)
CD16 <- subset(CD16, subset = nFeature_RNA > 500 & percent.mt.cd < 5)
EF16 <- subset(EF16, subset = nFeature_RNA > 500 & percent.mt.ef < 5)
A16 <- NormalizeData(A16)
CD16 <- NormalizeData(CD16)
EF16 <- NormalizeData(EF16)
A16 <- FindVariableFeatures(A16, selection.method = "vst", nfeatures = 2000)
CD16 <- FindVariableFeatures(CD16, selection.method = "vst", nfeatures = 2000)
EF16 <- FindVariableFeatures(EF16, selection.method = "vst", nfeatures = 2000)
all.genes1 <- rownames(A16)
all.genes2 <- rownames(CD16)
all.genes3 <- rownames(EF16)
A16 <- ScaleData(A16, features = all.genes1)
CD16 <- ScaleData(CD16, features = all.genes2)
EF16 <- ScaleData(EF16, features = all.genes3)
A16 <- RunPCA(A16, features = VariableFeatures(object = A16), npcs=50)
CD16 <- RunPCA(CD16, features = VariableFeatures(object = CD16), npcs=50)
EF16 <- RunPCA(EF16, features = VariableFeatures(object = EF16), npcs=50)
DimHeatmap(A16, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(A16, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(A16, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(A16, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(A16, dims = 37:45, cells = 500, balanced = TRUE)
DimHeatmap(CD16, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(CD16, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(CD16, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(CD16, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(CD16, dims = 37:45, cells = 500, balanced = TRUE)
DimHeatmap(EF16, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(EF16, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(EF16, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(EF16, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(EF16, dims = 37:45, cells = 500, balanced = TRUE)
A16 <- FindNeighbors(A16, dims = 1:27)
A16 <- FindClusters(A16, resolution = 1)
A16 <- RunUMAP(A16, dims = 1:27)
DimPlot(A16, reduction = "umap", label = T)
CD16 <- FindNeighbors(CD16, dims = 1:26)
CD16 <- FindClusters(CD16, resolution = 1)
CD16 <- RunUMAP(CD16, dims = 1:26)
DimPlot(CD16, reduction = "umap", label = T)
EF16 <- FindNeighbors(EF16, dims = 1:21)
EF16 <- FindClusters(EF16, resolution = 1)
EF16 <- RunUMAP(EF16, dims = 1:21)
DimPlot(EF16, reduction = "umap", label = T)

#Save E16.5 Cervical filtered data as combined biological replicates
saveRDS(A16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/16A_all.RDS")
saveRDS(CD16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/16CD_all.RDS")
saveRDS(EF16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/16EF_all.RDS")

rm(A16.data,C16.data,D16.data,E16.data,F16.data)
rm(A16,CD16,EF16)
```

```{r}
#Load, examine and filtering thoracic replicate 1 data (TA16, TB16)
TA16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/16TA/")
TA16 <- CreateSeuratObject(counts = TA16.data, project = "TA16")
TB16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/16TB/")
TB16 <- CreateSeuratObject(counts = TB16.data, project = "TB16")
TAB16 <- merge(TA16, y = TB16, add.cell.ids = c("16TA", "16TB"), project = "16TATB")
TAB16
table(TAB16$orig.ident)
TAB16[["percent.mt"]] <- PercentageFeatureSet(TAB16, pattern = "^mt-")
VlnPlot(TAB16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
TAB16 <- subset(TAB16, subset = nFeature_RNA > 200 & percent.mt < 8)
TAB16 <- NormalizeData(TAB16)
TAB16 <- FindVariableFeatures(TAB16, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(TAB16)
TAB16 <- ScaleData(TAB16, features = all.genes)
TAB16 <- RunPCA(TAB16, npcs = 75, features = VariableFeatures(object = TAB16))
DimHeatmap(TAB16, dims = 1:15, cells = 500, balanced = TRUE)
DimHeatmap(TAB16, dims = 16:30, cells = 500, balanced = TRUE)
DimHeatmap(TAB16, dims = 31:45, cells = 500, balanced = TRUE)
DimHeatmap(TAB16, dims = 46:60, cells = 500, balanced = TRUE)
DimHeatmap(TAB16, dims = 61:75, cells = 500, balanced = TRUE)
TAB16 <- FindNeighbors(TAB16, reduction = "pca", dims = 1:75)
TAB16 <- FindClusters(TAB16, resolution = 0.5)
TAB16 <- FindClusters(TAB16, resolution = 1)
TAB16 <- FindClusters(TAB16, resolution = 2)
TAB16 <- FindClusters(TAB16, resolution = 4)
TAB16 <- FindClusters(TAB16, resolution = 6)
TAB16 <- FindClusters(TAB16, resolution = 8)
TAB16 <- RunUMAP(TAB16, reduction = "pca", dims = 1:75)
DimPlot(TAB16, reduction = "umap", group.by = "RNA_snn_res.0.5", label = T)+NoLegend()
DimPlot(TAB16, reduction = "umap", group.by = "RNA_snn_res.1", label = T)+NoLegend()
DimPlot(TAB16, reduction = "umap", group.by = "RNA_snn_res.2", label = T)+NoLegend()
DimPlot(TAB16, reduction = "umap", group.by = "RNA_snn_res.4", label = T)+NoLegend()
DimPlot(TAB16, reduction = "umap", group.by = "RNA_snn_res.6", label = T)+NoLegend()
DimPlot(TAB16, reduction = "umap", group.by = "orig.ident", label = T)+NoLegend()
FeaturePlot(TAB16, features = "Slc17a6", order = T)
FeaturePlot(TAB16, features = "Slc32a1", order = T)
FeaturePlot(TAB16, features = "Rbfox3", order = T)
FeaturePlot(TAB16, features = "nCount_RNA", order = T)

#Save E16.5 thoracic filtered data as combined biological replicates (1st thoracic replicate)
saveRDS(TAB16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Seurat_Objects/16TATB_all.RDS")
rm(TA16.data,TB16.data,TAB16)
```

```{r}
#Load, examine and filtering thoracic replicate 2 data (16TC, 16TD)
TD16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16TD")
TD16 <- CreateSeuratObject(counts = TD16.data, project = "16TD")
TC16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16TC")
TC16 <- CreateSeuratObject(counts = TC16.data, project = "16TC")
TCD16 <- merge(TC16, y = TD16, add.cell.ids = c("16TC", "16TD"), project = "16TCTD")
TCD16
table(TCD16$orig.ident)
TCD16[["percent.mt"]] <- PercentageFeatureSet(TCD16, pattern = "^mt-")
VlnPlot(TCD16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
TCD16 <- subset(TCD16, subset = nFeature_RNA > 200 & percent.mt < 8)
TCD16 <- NormalizeData(TCD16)
TCD16 <- FindVariableFeatures(TCD16, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(TCD16)
TCD16 <- ScaleData(TCD16, features = all.genes)
TCD16 <- RunPCA(TCD16, npcs = 75, features = VariableFeatures(object = TCD16))
DimHeatmap(TCD16, dims = 1:15, cells = 500, balanced = TRUE)
DimHeatmap(TCD16, dims = 16:30, cells = 500, balanced = TRUE)
DimHeatmap(TCD16, dims = 31:45, cells = 500, balanced = TRUE)
DimHeatmap(TCD16, dims = 46:60, cells = 500, balanced = TRUE)
DimHeatmap(TCD16, dims = 61:75, cells = 500, balanced = TRUE)

VlnPlot(TCD16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

TCD16 <- FindNeighbors(TCD16, reduction = "pca", dims = 1:75)
TCD16 <- FindClusters(TCD16, resolution = 0.5)
TCD16 <- FindClusters(TCD16, resolution = 1)
TCD16 <- FindClusters(TCD16, resolution = 2)
TCD16 <- FindClusters(TCD16, resolution = 4)
TCD16 <- FindClusters(TCD16, resolution = 6)
TCD16 <- FindClusters(TCD16, resolution = 8)
TCD16 <- FindClusters(TCD16, resolution = 16)
TCD16 <- FindClusters(TCD16, resolution = 32)
TCD16 <- RunUMAP(TCD16, reduction = "pca", dims = 1:75)
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.0.5", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.1", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.2", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.4", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.6", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.8", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.16", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "RNA_snn_res.32", label = T)+NoLegend()
DimPlot(TCD16, reduction = "umap", group.by = "orig.ident", label = T)+NoLegend()
FeaturePlot(TCD16, features = "Slc17a6", order = T)
FeaturePlot(TCD16, features = "Slc32a1", order = T)
FeaturePlot(TCD16, features = "nCount_RNA", order = T)
FeaturePlot(TCD16, features = "nFeature_RNA", order = T)
FeaturePlot(TCD16, features = "Onecut1", order = T)
FeaturePlot(TCD16, features = "Zfhx3", order = T)
FeaturePlot(TCD16, features = "Nfib", order = T)

#Save E16.5 thoracic filtered data as combined biological replicates (2nd thoracic replicate)
saveRDS(TCD16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Seurat_Objects/16TCTD_all.RDS")
rm(TC16.data,TD16.data,TCD16)
```

```{r}
#Load, examine and filtering thoracic replicate 3 data (TE16, TF16)
TE16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16TE/")
TE16 <- CreateSeuratObject(counts = TE16.data, project = "TE16")
TE16[["percent.mt"]] <- PercentageFeatureSet(TE16, pattern = "^mt-")
VlnPlot(TE16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
TF16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16TF/")
TF16 <- CreateSeuratObject(counts = TF16.data, project = "TF16")
TF16[["percent.mt"]] <- PercentageFeatureSet(TF16, pattern = "^mt-")
VlnPlot(TF16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
TE16
TE16 <- subset(TE16, subset = nFeature_RNA > 3000 & percent.mt < 8) #Poor quality emulsion, salvage cells by increasing stringency
TE16
TE16 <- NormalizeData(TE16)
TE16 <- FindVariableFeatures(TE16, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(TE16)
TE16 <- ScaleData(TE16, features = all.genes)
TE16 <- RunPCA(TE16, npcs = 75, features = VariableFeatures(object = TE16))
DimHeatmap(TE16, dims = 1:15, cells = 500, balanced = TRUE)
DimHeatmap(TE16, dims = 16:30, cells = 500, balanced = TRUE)
DimHeatmap(TE16, dims = 31:45, cells = 500, balanced = TRUE)
DimHeatmap(TE16, dims = 46:60, cells = 500, balanced = TRUE)
DimHeatmap(TE16, dims = 61:75, cells = 500, balanced = TRUE)
TE16 <- FindNeighbors(TE16, reduction = "pca", dims = 1:75)
TE16 <- FindClusters(TE16, resolution = 0.5)
TE16 <- FindClusters(TE16, resolution = 1)
TE16 <- FindClusters(TE16, resolution = 2)
TE16 <- FindClusters(TE16, resolution = 4)
TE16 <- FindClusters(TE16, resolution = 6)
TE16 <- FindClusters(TE16, resolution = 8)
TE16 <- FindClusters(TE16, resolution = 16)
TE16 <- FindClusters(TE16, resolution = 32)
TE16 <- RunUMAP(TE16, reduction = "pca", dims = 1:75)
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.0.5", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.1", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.2", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.4", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.6", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.8", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.16", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "RNA_snn_res.32", label = T)+NoLegend()
DimPlot(TE16, reduction = "umap", group.by = "orig.ident", label = T)+NoLegend()
FeaturePlot(TE16, features = "nCount_RNA", order = T)
FeaturePlot(TE16, features = "nFeature_RNA", order = T)
FeaturePlot(TE16, features = "Onecut1", order = T)
FeaturePlot(TE16, features = "Zfhx3", order = T)
FeaturePlot(TE16, features = "Ebf1", order = T)
FeaturePlot(TE16, features = "Neurod2", order = T)
FeaturePlot(TE16, features = "Nfib", order = T)
FeaturePlot(TE16, features = "Slc17a6", order = T)
FeaturePlot(TE16, features = "Slc32a1", order = T)
FeaturePlot(TE16, features = "Slc5a7", order = T)
FeaturePlot(TE16, features = "Phox2a", order = T)
FeaturePlot(TE16, features = "Barhl1", order = T)
FeaturePlot(TE16, features = "Otp", order = T)

TF16
TF16 <- subset(TF16, subset = nFeature_RNA > 200 & percent.mt < 8)
TF16
TF16 <- NormalizeData(TF16)
TF16 <- FindVariableFeatures(TF16, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(TF16)
TF16 <- ScaleData(TF16, features = all.genes)
TF16 <- RunPCA(TF16, npcs = 75, features = VariableFeatures(object = TF16))
DimHeatmap(TF16, dims = 1:15, cells = 500, balanced = TRUE)
DimHeatmap(TF16, dims = 16:30, cells = 500, balanced = TRUE)
DimHeatmap(TF16, dims = 31:45, cells = 500, balanced = TRUE)
DimHeatmap(TF16, dims = 46:60, cells = 500, balanced = TRUE)
DimHeatmap(TF16, dims = 61:75, cells = 500, balanced = TRUE)

TF16 <- FindNeighbors(TF16, reduction = "pca", dims = 1:75)
TF16 <- FindClusters(TF16, resolution = 0.5)
TF16 <- FindClusters(TF16, resolution = 1)
TF16 <- FindClusters(TF16, resolution = 2)
TF16 <- FindClusters(TF16, resolution = 4)
TF16 <- FindClusters(TF16, resolution = 6)
TF16 <- FindClusters(TF16, resolution = 8)
TF16 <- FindClusters(TF16, resolution = 16)
TF16 <- FindClusters(TF16, resolution = 32)
TF16 <- RunUMAP(TF16, reduction = "pca", dims = 1:75)
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.0.5", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.1", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.2", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.4", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.6", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.8", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.16", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "RNA_snn_res.32", label = T)+NoLegend()
DimPlot(TF16, reduction = "umap", group.by = "orig.ident", label = T)+NoLegend()

#Save E16.5 thoracic filtered data as separate technical replicates (3rd thoracic replicate)
saveRDS(TE16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Seurat_Objects/16TE_all.RDS")
saveRDS(TF16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Seurat_Objects/16TF_all.RDS")
rm(TE16.data,TF16.data,TE16,TF16)
```

```{r}
#Load, examine and filtering thoracic replicate 4 data (TG16, TH16)
TG16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16TG/")
TG16 <- CreateSeuratObject(counts = TG16.data, project = "TG16")
TH16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16TH/")
TH16 <- CreateSeuratObject(counts = TH16.data, project = "TH16")
TGH16 <- merge(TG16, y = TH16, add.cell.ids = c("16TG", "16TH"), project = "16TGTH")
TGH16
table(TGH16$orig.ident)
TGH16[["percent.mt"]] <- PercentageFeatureSet(TGH16, pattern = "^mt-")
VlnPlot(TGH16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
TGH16 <- subset(TGH16, subset = nFeature_RNA > 200 & percent.mt < 8)
TGH16 <- NormalizeData(TGH16)
TGH16 <- FindVariableFeatures(TGH16, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(TGH16)
TGH16 <- ScaleData(TGH16, features = all.genes)
TGH16 <- RunPCA(TGH16, npcs = 75, features = VariableFeatures(object = TGH16))
DimHeatmap(TGH16, dims = 1:15, cells = 500, balanced = TRUE)
DimHeatmap(TGH16, dims = 16:30, cells = 500, balanced = TRUE)
DimHeatmap(TGH16, dims = 31:45, cells = 500, balanced = TRUE)
DimHeatmap(TGH16, dims = 46:60, cells = 500, balanced = TRUE)
DimHeatmap(TGH16, dims = 61:75, cells = 500, balanced = TRUE)
TGH16 <- FindNeighbors(TGH16, reduction = "pca", dims = 1:75)
TGH16 <- FindClusters(TGH16, resolution = 0.5)
TGH16 <- FindClusters(TGH16, resolution = 1)
TGH16 <- FindClusters(TGH16, resolution = 2)
TGH16 <- FindClusters(TGH16, resolution = 4)
TGH16 <- FindClusters(TGH16, resolution = 6)
TGH16 <- FindClusters(TGH16, resolution = 8)
TGH16 <- FindClusters(TGH16, resolution = 16)
TGH16 <- FindClusters(TGH16, resolution = 32)
TGH16 <- RunUMAP(TGH16, reduction = "pca", dims = 1:75)
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.0.5", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.1", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.2", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.4", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.6", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.8", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.16", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "RNA_snn_res.32", label = T)+NoLegend()
DimPlot(TGH16, reduction = "umap", group.by = "orig.ident", label = T)+NoLegend()
FeaturePlot(TGH16, features = "Onecut1", order = T)
FeaturePlot(TGH16, features = "Zfhx3", order = T)
FeaturePlot(TGH16, features = "Ebf1", order = T)
FeaturePlot(TGH16, features = "Neurod2", order = T)
FeaturePlot(TGH16, features = "Nfib", order = T)
FeaturePlot(TGH16, features = "Slc17a6", order = T)
FeaturePlot(TGH16, features = "Slc32a1", order = T)
FeaturePlot(TGH16, features = "Slc5a7", order = T)
```

```{r}
#Save E16.5 thoracic filtered data as combined biological replicates (4th thoracic replicate)
saveRDS(TGH16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Seurat_Objects/16TGTH_all.RDS")
rm(TG16.data,TH16.data,TGH16)
```

```{r}
#Load & filter additional cervical replicate (G16 + H16) plus three lumbosacral replicates (2x reactions per)
G16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16G/filtered_feature_bc_matrix")
H16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16H/filtered_feature_bc_matrix")
LA16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16LA/filtered_feature_bc_matrix")
LB16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16LB/filtered_feature_bc_matrix")
LC16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16LC/filtered_feature_bc_matrix")
LD16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16LD/filtered_feature_bc_matrix")
LE16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16LE/filtered_feature_bc_matrix")
LF16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/Final count matrices/16LF/filtered_feature_bc_matrix")
G16 <- CreateSeuratObject(G16.data, project = "G16")
H16 <- CreateSeuratObject(H16.data, project = "H16")
LA16 <- CreateSeuratObject(LA16.data, project = "LA16")
LB16 <- CreateSeuratObject(LB16.data, project = "LB16")
LC16 <- CreateSeuratObject(LC16.data, project = "LC16")
LD16 <- CreateSeuratObject(LD16.data, project = "LD16")
LE16 <- CreateSeuratObject(LE16.data, project = "LE16")
LF16 <- CreateSeuratObject(LF16.data, project = "LF16")
LB16 <- subset(LB16, subset = nFeature_RNA > 2500) #Poor quality emulsion; attempt to salvage some data by increasing stringency
GH16 <- merge(G16, y = H16, project = "E16GH")
LALB16 <- merge(LA16, y = LB16, project = "E16LALB")
LELF16 <- merge(LE16, y = LF16, project = "E16LELF")
LCLD16 <- merge(LC16, y = LD16, project = "E16LCLD")
GH16[["percent.mt.gh"]] <- PercentageFeatureSet(GH16, pattern = "^mt-")
LALB16[["percent.mt.lalb"]] <- PercentageFeatureSet(LALB16, pattern = "^mt-")
LCLD16[["percent.mt.lcld"]] <- PercentageFeatureSet(LCLD16, pattern = "^mt-")
LELF16[["percent.mt.lelf"]] <- PercentageFeatureSet(LELF16, pattern = "^mt-")
VlnPlot(GH16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.gh"), ncol = 3)
VlnPlot(LALB16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.lalb"), ncol = 3)
VlnPlot(LCLD16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.lcld"), ncol = 3)
VlnPlot(LELF16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.lelf"), ncol = 3)
GH16 <- subset(GH16, subset = nFeature_RNA > 500 & percent.mt.gh < 5)
LALB16 <- subset(LALB16, subset = nFeature_RNA > 500 & percent.mt.lalb < 5)
LCLD16 <- subset(LCLD16, subset = nFeature_RNA > 500 & percent.mt.lcld < 5)
LELF16 <- subset(LELF16, subset = nFeature_RNA > 500 & percent.mt.lelf < 5)
GH16 <- NormalizeData(GH16)
LALB16 <- NormalizeData(LALB16)
LCLD16 <- NormalizeData(LCLD16)
LELF16 <- NormalizeData(LELF16)
GH16 <- FindVariableFeatures(GH16, selection.method = "vst", nfeatures = 2000)
LALB16 <- FindVariableFeatures(LALB16, selection.method = "vst", nfeatures = 2000)
LCLD16 <- FindVariableFeatures(LCLD16, selection.method = "vst", nfeatures = 2000)
LELF16 <- FindVariableFeatures(LELF16, selection.method = "vst", nfeatures = 2000)
all.genes1 <- rownames(GH16)
all.genes2 <- rownames(LALB16)
all.genes3 <- rownames(LCLD16)
all.genes4 <- rownames(LELF16)
GH16 <- ScaleData(GH16, features = all.genes1)
LALB16 <- ScaleData(LALB16, features = all.genes2)
LCLD16 <- ScaleData(LCLD16, features = all.genes3)
LELF16 <- ScaleData(LELF16, features = all.genes4)
GH16 <- RunPCA(GH16, features = VariableFeatures(object = GH16), npcs=50)
LALB16 <- RunPCA(LALB16, features = VariableFeatures(object = LALB16), npcs=50)
LCLD16 <- RunPCA(LCLD16, features = VariableFeatures(object = LCLD16), npcs=50)
LELF16 <- RunPCA(LELF16, features = VariableFeatures(object = LELF16), npcs=50)
DimHeatmap(GH16, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(GH16, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(GH16, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(GH16, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(GH16, dims = 37:45, cells = 500, balanced = TRUE)
DimHeatmap(LALB16, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(LALB16, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(LALB16, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(LALB16, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(LALB16, dims = 37:45, cells = 500, balanced = TRUE)
DimHeatmap(LCLD16, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(LCLD16, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(LCLD16, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(LCLD16, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(LCLD16, dims = 37:45, cells = 500, balanced = TRUE)
DimHeatmap(LELF16, dims = 1:9, cells = 500, balanced = TRUE)
DimHeatmap(LELF16, dims = 10:18, cells = 500, balanced = TRUE)
DimHeatmap(LELF16, dims = 19:27, cells = 500, balanced = TRUE)
DimHeatmap(LELF16, dims = 28:36, cells = 500, balanced = TRUE)
DimHeatmap(LELF16, dims = 37:45, cells = 500, balanced = TRUE)
GH16 <- FindNeighbors(GH16, dims = 1:24)
GH16 <- FindClusters(GH16, resolution = 1)
GH16 <- RunUMAP(GH16, dims = 1:24)
DimPlot(GH16, reduction = "umap", label = T)
LALB16 <- FindNeighbors(LALB16, dims = 1:25)
LALB16 <- FindClusters(LALB16, resolution = 1)
LALB16 <- RunUMAP(LALB16, dims = 1:25)
DimPlot(LALB16, reduction = "umap", label = T)
LCLD16 <- FindNeighbors(LCLD16, dims = 1:24)
LCLD16 <- FindClusters(LCLD16, resolution = 1)
LCLD16 <- RunUMAP(LCLD16, dims = 1:24)
DimPlot(LCLD16, reduction = "umap", label = T)
LELF16 <- FindNeighbors(LELF16, dims = 1:30)
LELF16 <- FindClusters(LELF16, resolution = 1)
LELF16 <- RunUMAP(LELF16, dims = 1:30)
DimPlot(LELF16, reduction = "umap", label = T)
FeaturePlot(GH16, features = c("Rbfox3"), order = T)
FeaturePlot(LALB16, features = c("Rbfox3"), order = T)
FeaturePlot(LCLD16, features = c("Rbfox3"), order = T)
FeaturePlot(LELF16, features = c("Rbfox3"), order = T)
```

```{r}
#Save E16.5 cervical and lumbosacral filtered data as combined biological replicates (4th cervical replicate; #s 1-3 lumbosacral biological replicates)
saveRDS(GH16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/16GH_all.RDS")
saveRDS(LALB16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/16LALB_all.RDS")
saveRDS(LCLD16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/16LCLD_all.RDS")
saveRDS(LELF16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic spinal cord/16LELF_all.RDS")
rm(G16.data,H16.data,LA16.data,LB16.data,LC16.data,LD16.data,LE16.data,LF16.data)
rm(GH16,LALB16,LCLD16,LELF16)
```

```{r}
#Load & filter fourth lumbosacral replicate (2x reactions per)
LG16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16LG/")
LG16 <- CreateSeuratObject(counts = LG16.data, project = "LG16")
LH16.data <- Read10X("/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Final count matrices/16LH/")
LH16 <- CreateSeuratObject(counts = LH16.data, project = "LH16")
LGH16 <- merge(LG16, y = LH16, add.cell.ids = c("16LG", "16LH"), project = "16LGLH")
LGH16
table(LGH16$orig.ident)
LGH16[["percent.mt"]] <- PercentageFeatureSet(LGH16, pattern = "^mt-")
VlnPlot(LGH16, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
LGH16 <- subset(LGH16, subset = nFeature_RNA > 200 & percent.mt < 8)
LGH16 <- NormalizeData(LGH16)
LGH16 <- FindVariableFeatures(LGH16, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(LGH16)
LGH16 <- ScaleData(LGH16, features = all.genes)
LGH16 <- RunPCA(LGH16, npcs = 75, features = VariableFeatures(object = LGH16))
DimHeatmap(LGH16, dims = 1:15, cells = 500, balanced = TRUE)
DimHeatmap(LGH16, dims = 16:30, cells = 500, balanced = TRUE)
DimHeatmap(LGH16, dims = 31:45, cells = 500, balanced = TRUE)
DimHeatmap(LGH16, dims = 46:60, cells = 500, balanced = TRUE)
DimHeatmap(LGH16, dims = 61:75, cells = 500, balanced = TRUE)
LGH16 <- FindNeighbors(LGH16, reduction = "pca", dims = 1:75)
LGH16 <- FindClusters(LGH16, resolution = 0.5)
LGH16 <- FindClusters(LGH16, resolution = 1)
LGH16 <- FindClusters(LGH16, resolution = 2)
LGH16 <- FindClusters(LGH16, resolution = 4)
LGH16 <- FindClusters(LGH16, resolution = 6)
LGH16 <- FindClusters(LGH16, resolution = 8)
LGH16 <- FindClusters(LGH16, resolution = 16)
LGH16 <- FindClusters(LGH16, resolution = 32)
LGH16 <- RunUMAP(LGH16, reduction = "pca", dims = 1:75)
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.0.5", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.1", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.2", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.4", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.6", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.8", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.16", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "RNA_snn_res.32", label = T)+NoLegend()
DimPlot(LGH16, reduction = "umap", group.by = "orig.ident", label = T)+NoLegend()
FeaturePlot(LGH16, features = "Onecut1", order = T)
FeaturePlot(LGH16, features = "Zfhx3", order = T)
FeaturePlot(LGH16, features = "Ebf1", order = T)
FeaturePlot(LGH16, features = "Neurod2", order = T)
FeaturePlot(LGH16, features = "Nfib", order = T)
FeaturePlot(LGH16, features = "Slc17a6", order = T)
FeaturePlot(LGH16, features = "Slc32a1", order = T)
FeaturePlot(LGH16, features = "Slc5a7", order = T)

#Save E16.5 lumbosacral filtered data as combined biological replicates (4th lumbosacral replicate)
saveRDS(LGH16, "/Users/roomerb/Documents/Experiments/RNA-Seq/Embryonic_spinal_cord/Seurat_Objects/16LGLH_all.RDS")
rm(LG16.data,LH16.data)
rm(LGH16)
```

